[package]
name = "grand-toaster-protocol-server"
version = "0.1.0"
edition = "2021"

[profile.release]
strip = true

[dependencies]
notify = "6.1.1"
tokio = { version = "1.36.0", features = ["full"] }
